name: Ona CLI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-action:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        channel: [latest, stable]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ona CLI
        uses: ./
        with:
          token: ${{ secrets.ONA_TOKEN }}
          channel: ${{ matrix.channel }}

      - name: Verify CLI
        run: gitpod --help
